# How to use
pip  install -r requirements.txt

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [7]:
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
%matplotlib inline

In [8]:

df = pd.read_csv('../data/movies_2026.csv', encoding='latin-1')

In [9]:
df.head()

,id,budget,genres,homePage,productionCompany,productionCompanyCountry,productionCountry,revenue,runtime,video,...,releaseDate,voteAvg,voteCount,genresAmount,productionCoAmount,productionCountriesAmount,actorsAmount,castWomenAmount,castMenAmount,releaseYear
0,1627085,0.0,Drama|Crime,NaN,NaN,NaN,NaN,0.0,95,False,...,2026-02-01,0.0,0,2,0,0,8,2.0,5.0,2026.0
1,1626914,0.0,Animation,NaN,NaN,NaN,NaN,0.0,3,False,...,2026-02-01,0.0,0,1,0,0,4,0.0,0.0,2026.0
2,1626898,0.0,Animation,NaN,NaN,NaN,NaN,0.0,2,False,...,2026-02-01,0.0,0,1,0,0,3,0.0,0.0,2026.0
3,1626808,0.0,Thriller|Mystery|Documentary,NaN,NaN,NaN,NaN,0.0,5,False,...,2026-02-01,0.0,0,3,0,0,7,0.0,0.0,2026.0
4,1626678,0.0,Animation,NaN,NaN,NaN,NaN,0.0,12,False,...,2026-02-01,0.0,0,1,0,0,3,0.0,0.0,2026.0

In [10]:
#ejer1
print(f"El dataset tiene {df.shape[0]} filas y {df.shape[1]} columnas")

El dataset tiene 19883 filas y 28 columnas

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19883 entries, 0 to 19882
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         19883 non-null  int64
 1   budget                     19883 non-null  float64
 2   genres                     17918 non-null  str
 3   homePage                   5607 non-null   str
 4   productionCompany          14223 non-null  str
 5   productionCompanyCountry   11473 non-null  str
 6   productionCountry          16009 non-null  str
 7   revenue                    19883 non-null  float64
 8   runtime                    19883 non-null  int64
 9   video                      19397 non-null  object
 10  director                   18907 non-null  str
 11  actors                     17282 non-null  str
 12  actorsPopularity           17275 non-null  str
 13  actorsCharacter            17048 non-null  str
 14  originalTitle              19882 non-null  str
 15  title                      19882 non-null  str
 16  originalLanguage           19883 non-null  str
 17  popularity                 19883 non-null  float64
 18  releaseDate                19881 non-null  str
 19  voteAvg                    19883 non-null  float64
 20  voteCount                  19883 non-null  int64
 21  genresAmount               19883 non-null  int64
 22  productionCoAmount         19883 non-null  int64
 23  productionCountriesAmount  19883 non-null  int64
 24  actorsAmount               19883 non-null  int64
 25  castWomenAmount            19846 non-null  float64
 26  castMenAmount              19721 non-null  float64
 27  releaseYear                19881 non-null  float64
dtypes: float64(7), int64(7), object(1), str(13)
memory usage: 4.2+ MB

In [13]:
df.describe()

,id,budget,revenue,runtime,popularity,voteAvg,voteCount,genresAmount,productionCoAmount,productionCountriesAmount,actorsAmount,castWomenAmount,castMenAmount,releaseYear
count,1.988300e+04,1.988300e+04,1.988300e+04,19883.000000,19883.000000,19883.000000,19883.000000,19883.000000,19883.000000,19883.000000,19883.000000,19846.000000,19721.000000,19881.000000
mean,9.022402e+05,9.413280e+06,2.879213e+07,66.093799,26.248842,3.837069,675.927325,1.949253,1.972539,1.230247,1082.049640,3516.505996,8224.352061,2016.827222
std,6.848978e+05,2.774781e+07,1.109805e+08,50.089055,156.067177,3.397705,1938.194656,1.256225,2.312075,2.244688,26402.818732,47768.661984,71257.943156,12.838005
min,5.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1902.000000
25%,1.462195e+05,0.000000e+00,0.000000e+00,10.000000,0.054600,0.000000,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,2013.000000
50%,8.696230e+05,0.000000e+00,0.000000e+00,86.000000,8.502000,5.400000,6.000000,2.000000,1.000000,1.000000,9.000000,2.000000,3.000000,2021.000000
75%,1.589602e+06,1.000000e+06,3.306335e+05,103.000000,22.239000,6.800000,423.000000,3.000000,3.000000,1.000000,21.000000,6.000000,12.000000,2025.000000
max,1.627166e+06,3.800000e+08,2.847246e+09,750.000000,11474.647000,10.000000,30788.000000,16.000000,89.000000,155.000000,919590.000000,922162.000000,922017.000000,2026.000000

In [14]:
print("Valores nulos por columna:")
df.isnull().sum()

Valores nulos por columna:

id                               0
budget                           0
genres                        1965
homePage                     14276
productionCompany             5660
productionCompanyCountry      8410
productionCountry             3874
revenue                          0
runtime                          0
video                          486
director                       976
actors                        2601
actorsPopularity              2608
actorsCharacter               2835
originalTitle                    1
title                            1
originalLanguage                 0
popularity                       0
releaseDate                      2
voteAvg                          0
voteCount                        0
genresAmount                     0
productionCoAmount               0
productionCountriesAmount        0
actorsAmount                     0
castWomenAmount                 37
castMenAmount                  162
releaseYear                      2
dtype: int64

In [15]:
print("Columnas del dataset:")
print(df.columns.tolist())

Columnas del dataset:
['id', 'budget', 'genres', 'homePage', 'productionCompany', 'productionCompanyCountry', 'productionCountry', 'revenue', 'runtime', 'video', 'director', 'actors', 'actorsPopularity', 'actorsCharacter', 'originalTitle', 'title', 'originalLanguage', 'popularity', 'releaseDate', 'voteAvg', 'voteCount', 'genresAmount', 'productionCoAmount', 'productionCountriesAmount', 'actorsAmount', 'castWomenAmount', 'castMenAmount', 'releaseYear']